### ISSUE TITLE
jboss.socket.binding.port-offset not read properly

### ISSUE THREAD

**Issue by coladict** [wildfly/wildfly-arquillian#100]
Currently the Hibernate ORM project has some tests running using Wildfly that tries to launch the server using `-Djboss.socket.binding.port-offset=137`, however the test suite creates a [ManagedContainerConfiguration](https://github.com/wildfly/wildfly-arquillian/blob/master/container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedContainerConfiguration.java) in the side that runs the tests. The ManagedContainerConfiguration extends [CommonContainerConfiguration](https://github.com/wildfly/wildfly-arquillian/blob/master/common/src/main/java/org/jboss/as/arquillian/container/CommonContainerConfiguration.java#L38) which reads the `jboss.socket.binding.port-offset` system property from the **launcher** process, but that property is only set on the **launched** process, so the test suite always finds it to be 0.

The solution seems to be to have ManagedContainerConfiguration parse the `javaVmArguments` for any that would change relevant variables and recalculate them.

I discovered this because my tomcat server was running, when building and the Wildfly tests all failed. Then I learned that the `javaVmArguments` property wasn't read properly, because it contained comment nodes. That could be changed in `org.jboss.shrinkwrap.descriptor.spi.node.dom.XmlDomNodeImporterImpl.onlyTextChildren`. Then finally when the server was run with a port offset, the tests wouldn't start, because the [ManagedDeployableContainer](https://github.com/wildfly/wildfly-arquillian/blob/master/container-managed/src/main/java/org/jboss/as/arquillian/container/managed/ManagedDeployableContainer.java#L147) is looking for port 9990, when it should be port 10127.

**Comment by jamezp** [comment]
I'm not quit sure I understand. You should be able to add the property `javaVmArguments` in the `arquillian.xml` and it should be passed to the launched process. Do you by chance have an example configuration I could see?

One thing to note is that the `jboss.socket.binding.port-offset` only works if the expression is set on the `port-offset` attribute of the `socket-binding` resource.

**Comment by coladict** [comment]
[This is the one](https://github.com/hibernate/hibernate-orm/blob/55f7f71e04555f5f5a787161e145bda964033417/hibernate-orm-modules/src/test/resources/arquillian.xml).
You'd have to remove the comment node inside the property or it gets ignored.
If you're going to try and build it, the I'd go with `./gradlew hibernate-core:test --tests org.hibernate.jpa.test.cdi.BasicCdiTest` with JAVA_HOME pointing to JDK 8. But first you have to edit both `hibernate-orm-modules/src/test/resources/arquillian.xml` and `hibernate-core/src/test/resources/arquillian.xml` to remove the comment nodes from the property. You'll see it gets stuck unable to detect that Wildlfly is successfully launched.

**Comment by jamezp** [comment]
Excellent, thanks! I'll give it a test.

With regards to the XML comment. If the comments are making it into the `javaVMArguments` I'd consider it an Arquillian Core bug. I'll have a look though before creating any JIRA's.

**Comment by jamezp** [comment]
I'm closing this as it's quite old now. If this is still an issue please file it at https://issues.redhat.com/browse/WFARQ.
