### ISSUE TITLE
Exceptions never catched by IT tests

### ISSUE THREAD

**Issue by leccyril** [wildfly/wildfly-arquillian#101]
i have a configuration like arquillian.org , then i change weld container by  the following maven library 👍 `<dependency>
			<groupId>org.wildfly.arquillian</groupId>
			<artifactId>wildfly-arquillian-container-managed</artifactId>
			    <version>2.1.0.Alpha1</version>
			<scope>test</scope>
		</dependency>`

and use arquillian.xml then i just try to write throw new Exception in a test, and the test is not in failure any idea?

**Comment by jamezp** [comment]
Could you show the test method?

**Comment by leccyril** [comment]
@Test
    //@OperateOnDeployment("test")
    public void should_create_greeting() throws Exception{
    	System.out.println("test");
    	greeter.createGreeting("Earthling");
    	greeter.greet(System.out, "Earthling");
    	throw new NullPointerException();
}

**Comment by leccyril** [comment]
in test with weld embbeded it is working the exception is catched

**Comment by jamezp** [comment]
That should fail the build. Try something like `Assert.fail()` to see if that breaks it. If not my guess would be something in the test is not configured correctly.

**Comment by leccyril** [comment]
i want to make fail the build, but it does not do it.... in fact i detect a probleme because when i test method with null argument nothing append and test pass successfully, an di don't want it... i want when i throw an excption , i want have an error. In fact when a method like service.executeMethod(parameter) throw an exception we exit the code but test will write OK ... why i am doing it, imagine someone change a method and now throw exception because something wrong happen, the build will always work... i want when service send an exception the test will be in failure , for the moment it is not the case

**Comment by leccyril** [comment]
And the assert fail will work because all tests not fail.... good test or bad test

**Comment by leccyril** [comment]
And the test is very simple ! and i change a test with no container wildfly and if i throw an exception the test will FAIL => OK for me

**Comment by leccyril** [comment]
i test it with testNG because i all projects we have it is testNG used

**Comment by jamezp** [comment]
It seemed to work for me. Do you have an example of the project I could look at? 

My test was very simple:
```java
@RunWith(Arquillian.class)
public class SimpleServletTest {

    @Deployment
    public static WebArchive deployment() {
        return ShrinkWrap.create(WebArchive.class, "simple-servlet.war")
                .addPackages(true, SimpleServlet.class.getPackage());
    }

    @Test
    public void test() throws Exception {
        throw new NullPointerException();
    }
}
```

```
Results :

Tests in error: 
  SimpleServletTest.test:57 NullPointer

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.522 s
[INFO] Finished at: 2017-03-03T09:05:15-08:00
[INFO] Final Memory: 24M/246M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project simple-servlet: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jperkins/projects/jboss/examples/javaee/simple-servlet/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by leccyril** [comment]
`public class TestException extends Arquillian{

	private static String WEBAPP_SRC = "src/main/webapp";
	
	@Inject Greeter greeter;
	
	private static String POM_FILE = "pom.xml";
	private static String ARCHIVE_NAME = "test.war";
	
	@Deployment
    public static Archive<?> generateDefaultDeployment() {
		
		// Generate the default WAR used by all *IT tests using @OperateOnDeployment("AofWeb") annotation
		//LOGGER.info("Generating " + ARCHIVE_NAME + " archive ...");
		
		PomEquippedResolveStage pom = Maven.resolver().loadPomFromFile(POM_FILE);
		ScopeType[] scopes = {ScopeType.COMPILE, ScopeType.IMPORT, ScopeType.TEST}; // no SYSTEM and no PROVIDED
		File[] libs = pom.importDependencies(scopes).resolve().using(TransitiveStrategy.INSTANCE).asFile();
		
		WebArchive archive =  ShrinkWrap.create(WebArchive.class, ARCHIVE_NAME)
				.addClass(Greeter.class)
			     .addAsLibraries(libs)
		        .addAsWebInfResource(new File(WEBAPP_SRC, "WEB-INF/beans.xml"));
		archive.merge(ShrinkWrap.create(GenericArchive.class).as(ExplodedImporter.class)  
			    .importDirectory(WEBAPP_SRC).as(GenericArchive.class),  
			    "/", Filters.include(".*\\.(?i)(jpg|js|png|gif|bmp|html|xhtml|css)$"));  
				
		// No need to log the content anymore, the archive is kept in target directory 
		// "deploymentExportPath" variable in arquillian.xml
		System.out.println(archive.toString(true));
		
		return archive;
    }

    @Test
    //@OperateOnDeployment("test")
    public void should_create_greeting() throws Exception{
    	System.out.println("test");
    	greeter.createGreeting("Earthling");
    	greeter.greet(System.out, "Earthling");
    	//Assert.fail(greeter.createGreeting(null));
    	throw new Exception();

    }
}`

then pom.xml
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>sample.spnego</groupId>
	<artifactId>sample-app</artifactId>
	<packaging>war</packaging>
	<version>1.0</version>
	<name>sample-app</name>

	<dependencyManagement>
		<dependencies>
			
			<dependency>
				<groupId>org.jboss.spec</groupId>
				<artifactId>jboss-javaee-6.0</artifactId>
				<version>3.0.3.Final</version>
				<scope>provided</scope>
				<type>pom</type>
			</dependency>
			<dependency>
				<groupId>org.jboss.arquillian</groupId>
				<artifactId>arquillian-bom</artifactId>
				
				<version>1.1.12.Final</version>
				<scope>import</scope>
				<type>pom</type>
			</dependency>
			  <dependency>  
                <groupId>org.jboss.shrinkwrap.resolver</groupId>  
                <artifactId>shrinkwrap-resolver-bom</artifactId>  
                <version>2.2.6</version>  
                <type>pom</type>  
                <scope>import</scope>  
            </dependency>
		</dependencies>
	</dependencyManagement>




	<dependencies>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.5</version>
		</dependency>
		<dependency>
			<groupId>org.jboss.spec</groupId>
			<artifactId>jboss-javaee-6.0</artifactId>

			<type>pom</type>
			<scope>provided</scope>
		</dependency>















		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.10</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.arquillian.testng</groupId>
			<artifactId>arquillian-testng-container</artifactId>
			<scope>test</scope>
		</dependency>






		<dependency>
			<groupId>org.eu.ingwar.tools</groupId>
			<artifactId>arquillian-suite-extension</artifactId>
			<version>1.1.2</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.6.4</version>
			<scope>provided</scope>
		</dependency>
			<dependency>
    		<groupId>org.eclipse.aether</groupId>
    		<artifactId>aether-impl</artifactId>
    		<version>1.1.0</version>
		</dependency>
		 <dependency>
            <groupId>org.jboss.shrinkwrap.resolver</groupId>
            <artifactId>shrinkwrap-resolver-depchain</artifactId>
            <scope>test</scope>
            <type>pom</type>

        </dependency>

		<dependency>
			<groupId>org.wildfly.arquillian</groupId>
			<artifactId>wildfly-arquillian-container-managed</artifactId>
			    <version>1.0.0.Alpha1</version>
			<scope>test</scope>
		</dependency>
	</dependencies>



	<profiles>
		<profile>
			<id>integration</id>
			<build>
				<plugins>
					
					
					
					
					
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-failsafe-plugin</artifactId>
						<version>2.19.1</version>

						<configuration>
							<systemPropertyVariables>
								<jboss.server.log.dir>C:/dev/servers/wildfly-9.0.2.Final/standalone/log</jboss.server.log.dir>
								<arquillian.launch>jbossas-managed</arquillian.launch>
								<jbossas.startup.timeout>240</jbossas.startup.timeout>

							</systemPropertyVariables>
							<includes>
								<include>*.java</include>
							</includes>
							
						</configuration>
						<executions>
							<execution>
								<goals>
									<goal>integration-test</goal>
									<goal>verify</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>

		</profile>
	</profiles>
</project>
`
and arquillian.xml 

`<?xml version="1.0" encoding="UTF-8"?>
<arquillian xmlns="http://jboss.org/schema/arquillian"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://jboss.org/schema/arquillian http://jboss.org/schema/arquillian/arquillian_1_0.xsd">

	
	<defaultProtocol type="Servlet 3.0" />
        
    
	<engine>
	       <property name="deploymentExportPath">target/</property>
	</engine>
	

    
    
    <container qualifier="jbossas-managed" default="true">
        <configuration>
            <property name="jbossHome">${env.JBOSS_HOME}</property>
            <property name="serverConfig">standalone-real-continuous-integration.xml</property>
             
            <property name="allowConnectingToRunningServer">true</property>
        </configuration>
    </container>
    
    
    <container qualifier="jbossas-remote" default="false">
		<configuration>
			<property name="managementAddress">remoteHost</property>
			<property name="managementPort">9999</property>
		</configuration>
	</container>

    
</arquillian>`

i am not using junit but testNG, i will try junit just to see

working configuration

`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.arquillian.example</groupId>
  <artifactId>arquillian-tutorial</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>arquillian-tutorial</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  
   <dependencyManagement>
        <dependencies>
            
            <dependency>
                <groupId>org.jboss.spec</groupId>
                <artifactId>jboss-javaee-6.0</artifactId>
                <version>3.0.3.Final</version>
                <scope>provided</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>org.jboss.arquillian</groupId>
                <artifactId>arquillian-bom</artifactId>

                <version>1.1.12.Final</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
  <dependency>
            <groupId>org.jboss.spec</groupId>
            <artifactId>jboss-javaee-6.0</artifactId>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>
      <dependency>



   <groupId>org.jboss.arquillian.testng</groupId>
    <artifactId>arquillian-testng-container</artifactId>
    <scope>test</scope>
    
</dependency>
<dependency>
        <groupId>javax.enterprise</groupId>
        <artifactId>cdi-api</artifactId>
        <version>1.2</version>
    </dependency>
<dependency>
    <groupId>org.jboss.arquillian.container</groupId>
    <artifactId>arquillian-weld-ee-embedded-1.1</artifactId>
    <version>1.0.0.CR9</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-core</artifactId>
    <version>2.3.5.Final</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>1.6.4</version>
    <scope>test</scope>
</dependency>
   <dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.10</version>
			<scope>test</scope>
		</dependency>
    </dependencies>
    <build>
      <finalName>arquillian-tutorial</finalName>
      <plugins>
        <plugin>
          <artifactId>maven-war-plugin</artifactId>
          <version>2.4</version>
          <configuration>
            <failOnMissingWebXml>false</failOnMissingWebXml>
          </configuration>
        </plugin>
      </plugins>
    </build>
</project>
`

**Comment by leccyril** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<arquillian xmlns="http://jboss.org/schema/arquillian"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://jboss.org/schema/arquillian http://jboss.org/schema/arquillian/arquillian_1_0.xsd">

	
	<defaultProtocol type="Servlet 3.0" />
        
    
	<engine>
	       <property name="deploymentExportPath">target/</property>
	</engine>
	

    
    
    <container qualifier="jbossas-managed" default="true">
        <configuration>
            <property name="jbossHome">${env.JBOSS_HOME}</property>
            <property name="serverConfig">standalone-real-continuous-integration.xml</property>
             
            <property name="allowConnectingToRunningServer">true</property>
        </configuration>
    </container>
    
    
    <container qualifier="jbossas-remote" default="false">
		<configuration>
			<property name="managementAddress">remoteHost</property>
			<property name="managementPort">9999</property>
		</configuration>
	</container>

    
</arquillian>`

**Comment by leccyril** [comment]
i see it is working with Junit so it is the combinaison of wildfly-arquillian-container and testng container and testNg libraries

**Comment by leccyril** [comment]
when i change this 

`		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.9.13.6</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.arquillian.testng</groupId>
			<artifactId>arquillian-testng-container</artifactId>
			<scope>test</scope>
		</dependency>`

it is working the build failed

**Comment by jamezp** [comment]
Try a newer version of `wildfly-arquillian-container-managed`. In that first pom you're using 1.0.0.Alpha1 which is pretty old.

**Comment by jamezp** [comment]
Ah okay, so maybe it's a testng bug then.

**Comment by leccyril** [comment]
i am using 2.0.0 the 1.0.0 is juste a test, how i can do ? because i can't change all my testNG in Junit i have 2500 classes !!!

**Comment by leccyril** [comment]
OK with 6.8 version of testNG it is working

**Comment by jamezp** [comment]
What I meant was if an upgrade to testng fixes it, I would do that. I didn't mean to suggest you switch from testng to JUnit.

**Comment by leccyril** [comment]
finally i downgrade

`<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.10</version>
			<scope>test</scope>
		</dependency>`

to 

`<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.9.10</version>
			<scope>test</scope>
		</dependency>`

and now it is working thank you for your help !! have i to contact someone to specify the issue  ?

**Comment by jamezp** [comment]
I honestly have no idea. If a downgrade fixes it I would think the issues is with testng. I really know little about the internals of testng though.
