### ISSUE TITLE
Injected URL is always 127.0.0.1 (remote)

### ISSUE THREAD

**Issue by schnatterer** [wildfly/wildfly-arquillian#106]
I'm running integration tests on a remote wildFly that is not localhost/127.0.0.1. After changing the host name in `arquillian.xml` the application is deployed on the remote host but when injecting the URL in a test using `@ArquillianResource` it is always `127.0.0.1`.
This makes it impossible to write tests in client mode.

There seem to be other people with the same problem as well: [@ArquillianResource always injects localhost:8080 | JBoss Developer](https://developer.jboss.org/thread/274602)

Some more details: 
`arquillian.xml`:
```xml
    <container qualifier="wildFlyRemote">
        <configuration>
            <property name="username">${arquillian.wildfly.user}</property>
            <property name="password">${arquillian.wildfly.password}</property>
            <property name="managementAddress">${arquillian.wildfly.host:localhost}</property>
        </configuration>
        <protocol type="Servlet 3.0">
            <property name="host">${arquillian.wildfly.host:localhost}</property>
        </protocol>
    </container>
```
A (simplified) test:
```java
    @Test
    @RunAsClient
    public void redirects(@ArquillianResource URL contextRoot) throws Exception {
        LOG.info("contextRoot={}", contextRoot);
    }
```

pom.xml
```xml
            <dependency>
                <groupId>org.wildfly.arquillian</groupId>
                <artifactId>wildfly-arquillian-container-remote</artifactId>
                <version>2.1.0.Alpha2</version>
            </dependency>
            <dependency>
                <groupId>org.jboss.arquillian</groupId>
                <artifactId>arquillian-bom</artifactId>
                <version>1.1.13.Final</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>org.jboss.arquillian.junit</groupId>
                <artifactId>arquillian-junit-container</artifactId>
            </dependency>
            <dependency>
                <groupId>org.wildfly.arquillian</groupId>
                <artifactId>wildfly-arquillian-container-remote</artifactId>
                <version>2.0.2.Final</version>
                <scope>test</scope>
            </dependency>
```

CLI:
`mvn clean install -Darquillian.wildfly.host=172.17.0.2 -Darquillian.wildfly.user=admin -Darquillian.wildfly.password=secure -Darquillian.launch=wildFlyRemote`

Log Output:
`contextRoot=http://127.0.0.1:8080/83dc6769-010b-4d93-9431-d9677c6f76d4`

**Comment by jamezp** [comment]
For `Servlet 3.0` protocol host you shouldn't need to define the `host` property. It should automatically resolve. In my simple test it seemed to work fine. In fact I couldn't even get it to override the host in the URL.

One thing I do noice is you have two different versions of the `org.wildfly.arquillian:wildfly-arquillian-container-remote` defined. Maybe just try the 2.1.0.Apha2 version.

**Comment by jamezp** [comment]
What I mean is it seems the host and port for a URL cannot be overridden. They're discovered by reading the configuration of the undertow subsystem. How do you start WildFly?

**Comment by schnatterer** [comment]
Hey @jamezp,

thanks for your input.

> For Servlet 3.0 protocol host you shouldn't need to define the host property. It should automatically resolve.

When dropping the `host` property or the whole `protocol` tag, the tests fail with the following exception (I replaced the actual method signatures):

``` 
java.lang.IllegalStateException: Error launching test <method sigature>
Caused by: java.lang.IllegalStateException: Error launching request at http://127.0.0.1:8080/7e7f4af1-c36f-4740-a12d-5d506f274442/ArquillianServletRunner?outputMode=serializedObject&className=<method signature>. No result returned
``` 

> Maybe just try the 2.1.0.Apha2 version.

Sorry, copy and paste error. I'm on 2.1.0.Apha2.

>   How do you start WildFly?

I'm running the WildFly docker image, e.g. like so
```sh
CID=$(docker run -d jboss/wildfly:10.1.0.Final /bin/bash -c "/opt/jboss/wildfly/bin/add-user.sh -u admin -p secure && /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0")
WILDFLY_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CID)
mvn clean install -Darquillian.wildfly.host=$WILDFLY_IP -Darquillian.wildfly.user=admin -Darquillian.wildfly.password=secure
docker stop $CID
```
I'm not binding the ports (8080 and 9990) to localhost (`-p`) because I intend to run multiple builds in parallel. That's why I need to change the host in arquillian. 

> What I mean is it seems the host and port for a URL cannot be overridden. They're discovered by reading the configuration of the undertow subsystem. How do you start WildFly?

It seems the docker container does not know its external address. Do you have any ideas how to get around this issue?

**Comment by jamezp** [comment]
It looks like this is [hard-coded in the `ManagementClient`](https://github.com/wildfly/wildfly-arquillian/blob/master/common/src/main/java/org/jboss/as/arquillian/container/ManagementClient.java#L352-L355) to return `127.0.0.1` if the IP address on the binding is `0.0.0.0`. That looks a bit buggy to me and definitely should allow for an override.

I'm closing this as I've filed a JIRA to get it fixed, https://issues.jboss.org/browse/WFARQ-30. 

While maybe not possible the "fix" would be to specify the IP address of the docker container when binding to WildFly.
