### ISSUE TITLE
Allow user to override http-listener name from configuration file

### ISSUE THREAD

**Issue by dipak-pawar** [wildfly/wildfly-arquillian#110]
Currently wildfly arquillian is using name `default` for `http-listener`.

e.g. 
`<http-listener name="default" socket-binding="http"/> `

We have hard coded it in current implementation. You can look at [here](https://github.com/wildfly/wildfly-arquillian/blob/master/common/src/main/java/org/jboss/as/arquillian/container/ManagementClient.java#L197). 

Subsystem Configuration
```xml
<subsystem xmlns="urn:jboss:domain:undertow:3.1">  
    <buffer-cache name="default"/>  
    <server name="default-server">  
        <http-listener name="default" socket-binding="http"/>  
        <https-listener name="https" enabled-protocols="TLSv1" enabled-cipher-suites="TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA" security-realm="HTTPSRealm" socket-binding="https"/>  
        <host name="default-host" alias="localhost">  
            <filter-ref name="server-header"/>  
            <filter-ref name="x-powered-by-header"/>  
        </host>  
    </server>  
    <servlet-container name="default">  
        <jsp-config/>  
        <websockets/>  
    </servlet-container>  
    <filters>  
        <response-header name="server-header" header-name="Server" header-value="JBoss-EAP/7"/>  
        <response-header name="x-powered-by-header" header-name="X-Powered-By" header-value="Undertow/1"/>  
    </filters>  
</subsystem>  
```

Now If user want to use different name than `default` then he couldn't override host & port.

e.g.
`<http-listener name="http" socket-binding="http"/> `

Allow user to override http-listener name using arquillian.xml, so he can override ip & port when running it in remote mode.

**Comment by jamezp** [comment]
There's an issue on JIRA for this already https://issues.jboss.org/browse/WFARQ-31.
