### ISSUE TITLE
tests with @ShouldThrowException not correctly honored

### ISSUE THREAD

**Issue by McFoggy** [wildfly/wildfly-arquillian#116]
I am currently struggling to try to run microprofile TCKs tests on wildfly.

Some of the tests are using `@ShouldThrowException(value = DefinitionException.class, testable = true)` where `DefinitionException` is `javax.enterprise.inject.spi.DefinitionException`.

While tests run well on a weld container, I cannot make them run with a wildfly container.
I suspect:
- the expection to be wrapped but not unwrapped to check against the one defined inside `ShouldThrowException`
- the failing undeployment (because the deployment failed as expected) to also cause troubles.

Enclosed is a simple reproducer case (I also put it on github: https://github.com/McFoggy/wildfly-failing-deployment):
- `mvn clean test -Pweld` works as expected
- `mvn clean test -Pwildfly` fails for the test expecting the deployment failure

__reproducer app__: [failing-on-deployment.zip](https://github.com/wildfly/wildfly-arquillian/files/1498323/failing-on-deployment.zip)

**Comment by johnament** [comment]
To be clear - I made the API change in Arquillian that allows testable archives to throw exceptions.  Containers probably still need to do something to support this feature.  

The change, as noted by @McFoggy is that `@ShouldThrowException` now has a `testable` attribute, `false` by default, that is meant to support enhancing the archive.

**Comment by jamezp** [comment]
Looks like we do yes. It's new in 1.1.14 and currently wildfly-arquillian is targeting 1.1.13.

**Comment by jamezp** [comment]
Actually the 2.0 branch is targeting 1.1.11. Is there a reason a new feature went into a macro release? Feels like it should have been a minor release IMO.

**Comment by jamezp** [comment]
I'm going to close this issue and use https://issues.jboss.org/browse/WFARQ-36 for tracking purposes.
