### ISSUE TITLE
Warning: Bundles path is deprecated and no longer used.

### ISSUE THREAD

**Issue by watzerm** [wildfly/wildfly-arquillian#119]
Hello,

every time I execute my integration tests the following warning is displayed:
**Bundles path is deprecated and no longer used.**

In the following class: org/jboss/as/arquillian/container/managed/ManagedDeployableContainer.java beginning at line 93 I found:

      String bundlesPath = config.getBundlePath();
      if (bundlesPath == null || !bundlesPath.isEmpty()) {
        log.warning("Bundles path is deprecated and no longer used.");
      }

Please correct me if I'm wrong, but I suppose that the if test should be:

     if (bundlesPath != null && !bundlesPath.isEmpty()) { .....

**Comment by ctomc** [comment]
You are right. that is a bug.

Also at this point we should remove this check completly.

**Comment by watzerm** [comment]
OK, thank you!
Pull request created: https://github.com/wildfly/wildfly-arquillian/pull/120
