### ISSUE TITLE
Set logging.configuration for managed container

### ISSUE THREAD

**Issue by jwgmeligmeyling** [wildfly/wildfly-arquillian#158]
I've noticed that although a `logging.properties` file is available in the test suite, an managed container is actually not passed any available `logging.properties` file on the classpath. Neither it seems possible to set it in `arquillian.xml`. It would be nice to be able to configure the `logging.configuration`, or have it set to the available `logging.properties` file on the classpath by default, similarly to the.embedded container.

**Comment by jamezp** [comment]
What output are you looking to control with the `logging.properties` file? The logs via the container by chance?

**Comment by jamezp** [comment]
I'm closing this as it's been sitting around for a while. If this is still a request enhancement or feature request please file it at https://issues.redhat.com/browse/WFARQ.
