### ISSUE TITLE
-Djboss.socket.binding.port-offset argument is not handled

### ISSUE THREAD

**Issue by aldaris** [wildfly/wildfly-arquillian#45]
In ManagedDeployableContainer#isServerRunning it looks like the port check does not take port-offset into account.

It would be great if port-offset could be picked up, or even better: if wildfly-arquillian could find an offset that allows the WildFly instance to start up without any port clashes.

**Comment by jamezp** [comment]
There's no guarantee that property is used or that it's the property name used in a configuration file. The best that we could do is add a configuration property for the port-offset in the `ManagedContainerConfiguration`.

**Comment by jamezp** [comment]
If you use the `jboss.socket.binding.port-offset` it does look like the configuration will use that https://github.com/wildfly/wildfly-arquillian/blob/7738c07d4331b356e61c77b31e120f4ef579132a/common/src/main/java/org/jboss/as/arquillian/container/CommonContainerConfiguration.java#L39-L39. You'd need to make sure the system property is passed to the Arquillian so in Maven using the maven-surefire-plugin system properties.

If this is not what you meant feel free to open an issue at https://issues.jboss.org/projects/WFARQ
