### ISSUE TITLE
ServerSetup should be inherited

### ISSUE THREAD

**Issue by johnament** [wildfly/wildfly-arquillian#51]
In my codebase, I use a deep hierarchy of test classes for some reusability, and make the deployment consistent.

ServerSetup is not Inherited, as a result annotating a base class with my ServerSetup doesn't take effect.

**Comment by johnament** [comment]
Note that this is a need for us as we run different profiles.  It's not realistic to annotate every class with this, but we can use it in a base class.

**Comment by jamezp** [comment]
This should be solved now by the #52 PR right?

**Comment by jamezp** [comment]
Closing this as I think it's resolved.
