### ISSUE TITLE
new release soon?

### ISSUE THREAD

**Issue by The-Alchemist** [wildfly/wildfly-arquillian#65]
Even a SNAPSHOT would be nice.

The latest in Central looks to be 1.1.0.Alpha1: http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22wildfly-arquillian-container-remote%22

Is this the version to use for now?

**Comment by jamezp** [comment]
Hopefully this week. I'm not sure if we'll do a 1.1.0.Alpha2 and a 2.0.0.Alpha1 or just the 2.0.0.Alpha1. Note we're doing a new major to work with some changes in WildFly 10.

What version of WildFly are you running?

**Comment by The-Alchemist** [comment]
Wow, thanks for the quick reply. :)

WF 9.0.2.Final, soon we'll upgrade to 10.0.Final.

**Comment by jamezp** [comment]
Okay cool. That makes me think we should do one of each. Maybe even just move 1.1.x to Beta since there probably won't be a lot of changes going into it.

**Comment by ctomc** [comment]
Even current 1.0.x.Final versions of wildfly-arquillian adapters works fine with WildFly 10. 
So no need to wait for new release.

**Comment by jamezp** [comment]
Well embedded won't, but the others should.

**Comment by jamezp** [comment]
1.1.0.Beta1 has been released. I'm having some issues I need to figure out with the 2.0.0.Alpha1 release.

**Comment by The-Alchemist** [comment]
@jamezp : thanks, you're awesome!  Let me know if there's something I can test.
