### ISSUE TITLE
Setting managementPort programmatically

### ISSUE THREAD

**Issue by kaiwinter** [wildfly/wildfly-arquillian#72]
I'm using [testcontainers](https://github.com/testcontainers/testcontainers-java) to start a wildfly 10 docker image from my tests:
```java
@ClassRule
public static GenericContainer container = new GenericContainer("kaiwinter/wildfly-mariadb:latest");
```
I use `wildfly-arquillian-container-remote` to configure arquillian to use the wildfly in the docker container:
```xml
<container qualifier="wildfly-remote-docker" default="true">
  <protocol type="Servlet 3.0">
    <property name="host">11.1.3.56</property>
  </protocol>
  <configuration>
    <property name="managementAddress">11.1.3.56</property>  
    <property name="managementPort">9990</property>
    <property name="username">admin</property>
    <property name="password">Admin#123</property>
  </configuration>
</container>
```

This works when I let testcontainers use the fixed port 9990. But the docker host is a shared resource so I want to use a random port here. After the ClassRule I want to do something like the following:

```java
static {
  container.start();
  Integer mappedPort = container.getMappedPort(9990); // will return the actual random port
  RemoteContainerConfiguration.setManagementPort(mappedPort);
}
```
Is there a way to call `setManagementPort(mappedPort)` on the `RemoteContainerConfiguration`? How can I access that class from my test (I'm using the `@RunWith` and `@Deployment` annotations)?

**Comment by jamezp** [comment]
I don't think there is a way to do that. The configuration is created from the `arquillian.xml` file. I don't think we want to expose that `RemoteContainerConfiguration` as it should be _immutable_ after the container has been set up.

I don't know anything about the docker testcontainers, but if it helps in the `arquillian.xml` you can use system properties. So you could do something like `<property name="managementPort">${testcontainer.mapped.port:9990}</property>` where `testcontainer.mapped.port` is a system property and `9990` is the default if the system property is not found.

Also by default the configurations port is set like
```java
managementPort = 9990 + Integer.decode(System.getProperty("jboss.socket.binding.port-offset", "0"));
```
If the testcontainers can handle some kind of offset parameter that could work too if you set the `jboss.socket.binding.port-offset` in the `maven-surefire-plugin` system properties.

**Comment by kaiwinter** [comment]
Thank you for that pointer. But I had no success setting the variable in my unit test. Seems as it is evaluated before I can set it. I run the tests from my IDE and the docker container has to be started first by the test.
 
But I found a solution on [stackoverflow](http://stackoverflow.com/questions/27043300/arquillian-programmatic-configuration) which suggests the use of a `LoadableExtension`. Now I'm starting the docker container from that extension and override the `managementPort` in there. It's not the best solution because it needs additional classes but it works...

**Comment by jamezp** [comment]
I don't know much about it, but have you looked at [Arquillian Cube](http://arquillian.org/modules/cube-extension/)?
