### ISSUE TITLE
2.0.0.Final does not remove deployment from domain

### ISSUE THREAD

**Issue by smiklosovic** [wildfly/wildfly-arquillian#76]
I am writing my own tooling which is able to start and stop jboss / eap / as7 / wildfly and manage their lifecycle   and deploy and undeploy things there. I am basically not using Arquillian runtime at all and I am able to encapsulate whole interaction with containers just by writing some wrappers around ManagementClient and ArchiveDeployer and so on so I can manage containers very easilly just from java / groovy / scala itself without arquillian at all.

The thing is that once I deploy something into some server group and I undeploy it by current domain ArchiveDeployer, it is _undeployed_ as such but in Wildfly 10, that deployment is still there but it is "unassigned" so once I execute deployment again, it fails because it tells me that such archive is already there.

You do not remove deployment after you undeploy it so I extended domain ArchiveDeployer and overrided undeploy method and added removing plan. After that I am able to deploy and undeploy as many times I want.

This should be added into this extension as well.

https://gist.github.com/smiklosovic/900f6547276252555cf9f761ae2109ce#file-archivedeployer-java-L20-L37

**Comment by jamezp** [comment]
Nice catch, thanks! I've been thinking about using plain operations instead of the deployment plan anyway. Either way it looks like it needs to be fixed.

OT: Are you using the launcher api, `DomainCommandBuilder` or `StandaloneCommandBuilder`, to create launch command/process?

**Comment by smiklosovic** [comment]
No I do not use it, but I have something mine and that is more or less the same thing. I am basically reconstructing what is in the end the final command executed in standalone.sh or domain.sh

**Comment by jamezp** [comment]
FWIW that's what the launcher API does is just attempt to create the same output the `standalone.sh` or `domain.sh` would do. The license does appear to be wrong on it, it really should be ASLv2... ...anyway I digress :)

Sounds pretty interesting.

**Comment by dmaidaniuk** [comment]
Hi,

Any chance that this bug with not undeployed but just unassigned artifact will be fixed soon?
Our project also affected by `wildfly-arquillian-container-domain-remote` wrong behavior.

Regards,
Dmytro

**Comment by jamezp** [comment]
Yes this is something I'll have to look into soon. I'm considering making a change away from the `ArchiveDeployer` to using the `DeploymentManager` from the [WildFly Plugin Core](https://github.com/wildfly/wildfly-maven-plugin/tree/master/corel).

**Comment by dmaidaniuk** [comment]
Hi @jamezp,

Good to hear this. We used workaround based on Wildfly maven plugin for this issue. But it not cover all our needs unfortunately. Thus we awaiting for fixing this bug.

Regards,
Dmytro

**Comment by aymen083** [comment]
Hello i have the same problem with 2.0.2.
Any info about implementing the remove for remote domaine ?

Thanks,
Aymen

**Comment by jamezp** [comment]
I guess I should really look at these open issues. I often forget about them :) It should be fixed in 2.1.0.CR1.
