### ISSUE TITLE
Override managementPort and managementAddress via system property

### ISSUE THREAD

**Issue by Vampire** [wildfly/wildfly-arquillian#79]
Our Arquillian tests run find without any `arquillian.xml`. I'd like to keep it that way, but currently it is not possible. The tests run only with the default host and port `127.0.0.1:9990`. I'd like to be able to specify those values via system property. These values must be configurable, as developer machines could be setup differently and the build server runs the tests on another machine entirely that is dedicated to run a WildFly for integ tests. Currently I have to generate the corresponding `arquillian.xml` from the properties, but it would be more convenient to be able to just override those values with system properties that I give the test task.

**Comment by bartoszmajsak** [comment]
I think there is no need for generating `arquillian.xml` files for each and every case. You can have parametrized file, like

```xml
  <container qualifier="wildfy" default="true">
    <configuration>
      <property name="managementAddress">${WF_MGMT_ADDR:127.0.0.1}</property>
      <property name="managementAddress">${WF_MGMT_PORT:9990}</property>
    </configuration>
  </container>
```

Could be that you would have to prefix those variables with `env` -> `${env.WF_MGMT_ADDR:127.0.0.1}`. I don't remember by heart.

HTH

**Comment by feskehau** [comment]
With this you dont need an arquillian.xml to set properties:

You can set thems in the surefire plugin (here the qualifier will be set to wildfly)
``` xml
<plugins>
    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
            <trimStackTrace>false</trimStackTrace>
            <forkMode>always</forkMode>
            <systemPropertyVariables>
                <arq.container.wildfly.default>true</arq.container.wildfly.default>
                <arq.container.wildfly.configuration.managementPort>${wildfly_management_port}</arq.container.wildfly.configuration.managementPort>
                <arq.container.wildfly.configuration.managementAddress>${wildfly_management_address}</arq.container.wildfly.configuration.managementAddress>
                <arq.container.wildfly.configuration.managementProtocol>${wildfly_management_protocol}</arq.container.wildfly.configuration.managementProtocol>
                <arq.container.wildfly.configuration.username>${wildfly_management_username}</arq.container.wildfly.configuration.username>
                <arq.container.wildfly.configuration.password>${wildfly_management_password}</arq.container.wildfly.configuration.password>
            </systemPropertyVariables>
            <redirectTestOutputToFile>false</redirectTestOutputToFile>
        </configuration>
    </plugin>
</plugins>
```

To provide default values you add them to properties (Which can belong to the entire pom, or just the profile):
``` xml
        <profile>
            <id>arquillian-wildfly10-remote</id>
            
            <properties>
                <wildfly_management_address>127.0.0.1</wildfly_management_address>
                <wildfly_management_port>9990</wildfly_management_port>
                <wildfly_management_username>admin</wildfly_management_username>
                <wildfly_management_password>password</wildfly_management_password>
                <wildfly_management_protocol>http-remoting</wildfly_management_protocol>
            </properties>
```

These default properties can be overwritten by giving them to maven, here im overriding the password:
`$ mvn compile -Dwildfly_management_password=someOtherPassword`

**Comment by jamezp** [comment]
This is quite old at this point. If this is still an issue please file it at https://issues.redhat.com/browse/WFARQ.
