### ISSUE TITLE
wildfly-arquillian don't include the license file

### ISSUE THREAD

**Issue by puntogil** [wildfly/wildfly-arquillian#82]
Hi
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
Thanks in advance
Regards

**Comment by puntogil** [comment]
Sorry for the noise

**Comment by rhusar** [comment]
Its here https://github.com/wildfly/wildfly-arquillian/blob/master/LICENSE.txt right?

**Comment by puntogil** [comment]
yes
