### ISSUE TITLE
Not possible to pass empty jbossArguments

### ISSUE THREAD

**Issue by tremes** [wildfly/wildfly-arquillian#96]
Suppose I want to define following property in my arquillian.xml container configuration:
`<property name="jbossArguments">${additional.jboss.args}</property>`
By default I would like to have this property empty which is not possible because container won't start succesfully (it will get property with empty key and empty value).

**Comment by tremes** [comment]
https://github.com/wildfly/wildfly-arquillian/pull/97

**Comment by jamezp** [comment]
Moved to JIRA https://issues.jboss.org/browse/WFARQ-21
